### PR TITLE
Add "not latest" warning to all specs and remove latest.html

### PR DESCRIPTION
**Pull request by turt2live**
The latest.html redirects were handled back in Matrix 1.1's release.

Fixes https://github.com/matrix-org/matrix.org/issues/1235

Preview: https://pr1239--matrix-org-previews.netlify.app

### CODE REVIEW

**Comment by turt2live** [comment]
I'm not fixing typos on this - suspect it's fallout from https://github.com/crate-ci/typos/issues/411

**Comment by aaronraimist** [comment]
Those words are actually misspelled though. Typos just didn't find them due to that bug.

**Comment by afranke** [comment]
LGTM.

@aaronraimist would you mind submitting a PR to fix those typos that fell through?

**Review by afranke — APPROVED** [review]

**Review by afranke — CHANGES_REQUESTED** [review]
Actually `latest.json` is still being linked from `scripts/update_docs.sh`. Can you remove that line from the script?

**Comment by afranke** [comment]
Make that two lines, the mkdir becomes moot as well.

**Comment by afranke** [comment]
Can you please also add a rule for `latest.html` alongside [the existing “latest” rules](https://github.com/matrix-org/matrix-ansible-private/blob/main/roles/apache/templates/sites/matrix.org.conf.j2#L114)?

**Comment by afranke** [comment]
Huh, the ones that exist should actually already cover this. Sorry, I was mislead by the 404 on the Netlify preview.

**Comment by turt2live** [comment]
> Those words are actually misspelled though. Typos just didn't find them previously due to that bug.

They're valid, but strictly out of scope of this PR.

**Comment by turt2live** [comment]
> Actually latest.json is still being linked from scripts/update_docs.sh. Can you remove that line from the script?

@afranke I don't think this is the same `latest.json`? I'm working in `unstyled_docs/spec` whereas the script uses `unstyled_docs/api` (which doesn't exist, but I assume it exists at build time).

**Comment by afranke** [comment]
No, `unstyled_docs/api/` is where the link ends up. It **is** that same `latest.json` file that is linked *to*. In any case, just like the rest of this MR, this is about ancient references to the latest version of the spec that has become irrelevant with the new spec website. More specifically, this was for Rapidoc to use, but Rapidoc now points at the new website. It needs to go.

**Comment by turt2live** [comment]
or can we just remove the whole 4 lines?

**Comment by afranke** [comment]
The `mkdir` needs to be tweaked, and the `ln` line removed. I can do it, if you're ok with me pushing to your branch. We are not removing more as the rest is still needed for Rapidoc setup. It’s this:

```
diff --git a/scripts/update_docs.sh b/scripts/update_docs.sh
index c15b184f7..29157180a 100755
--- a/scripts/update_docs.sh
+++ b/scripts/update_docs.sh
@@ -25,8 +25,7 @@ cd "$(dirname "$(dirname "${SELF}")")"
 
 # Set up foundations for RapiDoc API playground
 rm -fr unstyled_docs/api/client-server
-mkdir -p unstyled_docs/api/client-server/json
-ln -s ../../../spec/client_server/latest.json unstyled_docs/api/client-server/json/api-docs.json
+mkdir -p unstyled_docs/api/client-server
 
 # copy the unstyled docs and add the styling
 rm -rf content/docs
```

**Comment by turt2live** [comment]
yes, please do push to the branch :D 

(I still don't really understand the changes needed)

**Review by afranke — APPROVED** [review]

**Comment by afranke** [comment]
We’re all good now. If that works for you, you can squash & merge.

**Pull request merged**
