### PR TITLE
Added Project synapse-admin to /projects/other

### PR DESCRIPTION
**Pull request by Supereuro**

### CODE REVIEW

**Comment by aaronraimist** [comment]
It looks like the app is called Matrix Admin not Synapse Admin.

(Synapse Admin is also already a thing so if it is called Synapse Admin that would be a bit confusing https://github.com/Awesome-Technologies/synapse-admin/)

**Comment by Supereuro** [comment]
Changed the Projectname anf file to Matrix Admin

**Comment by Supereuro** [comment]
Any update on this Pull request?

**Comment by thibaultamartin** [comment]
Hi Supereuro, sorry for taking this long to review your PR.

Having a companion app to administrate your Synapse server is great, congrats for developing it!
I'm a little wary of the name: Matrix is a protocol, and the admin APIs of Synapse are not part of it. It seems abusive to call the companion app Matrix Admin.

Can you rebrand to something that reflects this?

**Comment by thibaultamartin** [comment]
That would work for me, thanks!

**Comment by Supereuro** [comment]
Ok done!

**Comment by thibaultamartin** [comment]
Thank you, keep hacking on cool projects like this one!

**Pull request merged**
