### PR TITLE
Allow tabbing to ecosystem links in the header

### PR DESCRIPTION
**Pull request by jplatte**

### CODE REVIEW

**Comment by thibaultamartin** [comment]
https://user-images.githubusercontent.com/1688309/235621235-1f588957-14ff-4288-83e5-2e0889ef7749.mov

Tab navigation shows the menu, but it doesn't seem to select the label. I don't know if this gets in the way of assistive technologies

**Comment by thibaultamartin** [comment]
Apparently voiceover is not too happy with the hidden checkbox :|

https://user-images.githubusercontent.com/1688309/235623045-3d9ae776-a69d-4e33-90a5-d46f038292d2.mp4

**Comment by jplatte** [comment]
Seems like a case of needing an `aria-label` or whatever it's called?

**Comment by thibaultamartin** [comment]
Just gave it a go and it seems that's still confusing voiceover in the same way

**Comment by jplatte** [comment]
What did you try exactly? I'm sure there's some (combination of) aria labels that fixes this. It's just about presenting a checkbox as a menu toggle, doesn't seem super crazy..

**Comment by thibaultamartin** [comment]
Hm your branch untouched does seem to work with Safari… I wonder if that's a Firefox bug?

**Comment by MTRNord** [comment]
> Hm your branch untouched does seem to work with Safari… I wonder if that's a Firefox bug?

I wonder if this should be reported via https://webcompat.com/ or bugzilla 🤔

**Pull request merged**
