### PR TITLE
Add building the implementation guides to CI

### PR DESCRIPTION
**Pull request by erikjohnston**
I think this works?

### CODE REVIEW

**Comment by benparsons** [comment]
This will result in the output being on the same domain?

**Comment by erikjohnston** [comment]
There's a PR up to provision a spec.matrix.org which will have `/book` and `/guides` point at this, but yeah, it'll also be around on matrix.org. This just seemed like the easiest way to get going

**Comment by erikjohnston** [comment]
Woo, looks like it finally is doing the right thing!

**Comment by erikjohnston** [comment]
It worked! https://matrix.org/implementation-guides/server/ :tada:

**Pull request merged**
