### PR TITLE
I'd like to be a bigproject as well

### PR DESCRIPTION
**Pull request by f0x52**
Benpa told the categorization was arbitrary, so here's my pr

### CODE REVIEW

**Comment by benparsons** [comment]
I'll review the big list before long. (Just acknowledging that this PR is not simply being ignored!)

There are a couple of changes I want to make to that section. I also want to add, the list was not arbitrary, it was the best assessment I could make as of April 2018.

**Comment by f0x52** [comment]
whoops, I should've branched these new commits

**Comment by richvdh** [comment]
@benparsons @f0x52 what's the state of play here?

**Comment by benparsons** [comment]
@f0x52 I'm going to close this without merging for now. Let's chat again when the new neo is ready to show.

**Pull request closed without merging**
