### PR TITLE
Try to fix Thunderbird redirect

### PR DESCRIPTION
**Pull request by freaktechnik**
Preview: https://pr1318--matrix-org-previews.netlify.app

### CODE REVIEW

**Comment by afranke** [comment]
:thinking: Something must still be missing, the preview shows a 404.

Don’t mind the spell check CI step failing, that’s from an unrelated commit in master.

**Comment by afranke** [comment]
What happens if you remove the file altogether? Please test locally before pushing.

**Comment by thibaultamartin** [comment]
> 🤔 Something must still be missing, the preview shows a 404.

I pulled the latest changes and ran `npm run develop` in the `gatsby/` folder, http://localhost:8000/docs/projects/client/thunderbird seems to work. I get to this page by clicking the link in http://localhost:8000/docs/projects/try-matrix-now

When you mention the preview, you refer to netlify?

**Comment by afranke** [comment]
> When you mention the preview, you refer to netlify?

Yes.

**Comment by afranke** [comment]
https://pr1318--matrix-org-previews.netlify.app/docs/projects/client/thunderbird is 404, linked from https://pr1318--matrix-org-previews.netlify.app/docs/projects/try-matrix-now

**Comment by freaktechnik** [comment]
Weirdly on netlify https://pr1318--matrix-org-previews.netlify.app/page-data/docs/projects/client/mozilla-thunderbird/page-data.json exists, while on matrix.org it is https://matrix.org/page-data/docs/projects/client/thunderbird/page-data.json

From what I can tell the branch state that this is based on should generate the latter.

**Comment by afranke** [comment]
Maybe rerun the action, just to see?

**Comment by thibaultamartin** [comment]
> Maybe rerun the action, just to see?

I must be doing something wrong, after re-running the rebuild of the website if I try to re-run the deployment to Netlify it is simply skipped

**Comment by freaktechnik** [comment]
I think it did re-build and deploy after my merge, however if this is a caching issue it still persists. It might only re-build that page if the Thunderbird md is touched, and somehow the last PR didn't make it into the cache yet?

**Comment by freaktechnik** [comment]
The netlify preview is now behaving correctly for me.

**Comment by thibaultamartin** [comment]
It does indeed, thanks @freaktechnik!

**Pull request merged**
