### PR TITLE
Add SchildiChat

### LINKED ISSUE #932: Add SchildiChat
Please include Schildi Chat, a fork of Element in https://matrix.org/clients
Schildi Chat is available on Android, Desktop and Web.
Official Website: https://schildi.chat
Official Website: https://github.com/SchildiChat

### PR DESCRIPTION
**Pull request by vachan-maker**
Fix #932

### CODE REVIEW

**Comment by vachan-maker** [comment]
When will this be merged? Is there anything that needs to be changed?

**Comment by SpiritCroc** [comment]
Hi, cool you made this PR! Would have been nice if you had tagged us, so that we can review this... :)

After a quick skim, I note the following:
- It seems a little odd to me to use schildichat.mdx for the web/desktop variant, given that historically, SchildiChat first was the Android client, and later the web/desktop variant was added
- Please don't put a space in my name
- Missing author of SchildiChat Web/Deskop: @su-ex
- Where do the description texts come from? Parts of it sound familiar to what we have on our git and/or website, but parts of it sound unfamiliar

**Comment by vachan-maker** [comment]
@SpiritCroc 
I have updated the files. Sorry for not informing you. Is su-ex also the author for the mobile app? I added su-ex to the mobile app as well. The file names have also been changed.
The description is from the website, github repo and from other projects.

**Comment by SpiritCroc** [comment]
@su-ex and I did think some more about what we want we want to put in there, if you cherry-pick following commit to your PR, we're happy with it: https://github.com/SpiritCroc/matrix.org/commit/schildichat
Thank you!

**Comment by vachan-maker** [comment]
@SpiritCroc Made the changes. I don't know how to delete the .png files. Could you tell me how?
Also please proofread once again
Thanks

**Comment by SpiritCroc** [comment]
> @SpiritCroc Made the changes. I don't know how to delete the .png files. Could you tell me how?
> Also please proofread once again
> Thanks

I'm not familiar with github possibilities to create git commits, so I created a [pull-request to your repo](https://github.com/vachan-maker/matrix.org/pull/1) with the remaining changes. If you accept my pull request for your repo, it will be included in this pull request as well, I think.

**Comment by vachan-maker** [comment]
@SpiritCroc PR merged!

**Comment by SpiritCroc** [comment]
Thank you!
This looks fine from our side now.

**Review by benparsons — APPROVED** [review]
lgtm

**Pull request merged**
