### PR TITLE
Redirect for categories

### PR DESCRIPTION
**Pull request by laurencegill**
Fixes https://github.com/matrix-org/matrix.org/issues/1955

### CODE REVIEW

**Comment by thibaultamartin** [comment]
Does it work if urls have a trailing slash too?

**Comment by laurencegill** [comment]
> Does it work if urls have a trailing slash too?

It does not :smile: but I can add it?

**Comment by thibaultamartin** [comment]
That would be useful yes, please :)

**Review by thibaultamartin — APPROVED** [review]
LGTM, thanks Laurence

**Pull request merged**
