### PR TITLE
Publish TWIM 20220812

### PR DESCRIPTION
**Pull request by anoadragon453**

### CODE REVIEW

**Comment by anoadragon453** [comment]
The other spell checking error (`tha'`) is a false positive.

**Comment by anoadragon453** [comment]
In which I remember that this will now cause CI to fail for all eternity :facepalm:

**Comment by aaronraimist** [comment]
@anoadragon453 https://github.com/matrix-org/matrix.org/blob/master/.github/_typos.toml#L5-L10

**Comment by anoadragon453** [comment]
@aaronraimist [Fixed](https://github.com/matrix-org/matrix.org/pull/1400), thanks!

**Pull request merged**
