### PR TITLE
Add a thumbnail for SMS bridges on matrix.org/bridges

### PR DESCRIPTION
**Pull request by anoadragon453**

### CODE REVIEW

**Review by benparsons — APPROVED** [review]
lgtm

**Comment by anoadragon453** [comment]
image

Hmm, for some reason it's still not being picked up on the bridges page though.

**Comment by benparsons** [comment]
It hasn't been merged or deployed? Is this done, or still draft?

**Comment by anoadragon453** [comment]
> It hasn't been merged or deployed? Is this done, or still draft?

Sorry, my screenshot was from a local instance of `gatsby develop` :slightly_smiling_face:

**Comment by anoadragon453** [comment]
That seems to work, thanks!

**Pull request merged**
