### PR TITLE
fix: top page horizontal scroll bar issue

### PR DESCRIPTION
**Pull request by konan-5**

### CODE REVIEW

**Comment by MTRNord** [comment]
Hi :) thanks for your contribution. We are currently still at v0.18.0 of Zola meaning we still require the value to be `generate_feeds = true`. Could you also make sure to not commit the zola submodule please? :) It seems to be not complete anyway in its current form as it doesn't point anywhere.

**Review by MTRNord — CHANGES_REQUESTED** [review]
See my other comment please :)

**Comment by konan-5** [comment]
hello @MTRNord 
thank you for your reply
I rebased commit

**Comment by konan-5** [comment]
Pushed again, please check :)

**Comment by konan-5** [comment]
hello @MTRNord 
did you have a good weekend?
could you drop any message?

**Review by MTRNord — APPROVED** [review]

**Pull request merged**
