### PR TITLE
DittoClient: Remove URL https://dittochat.org/

### PR DESCRIPTION
**Pull request by jaller94**
The URL is unavailable and no website is mentioned on the linked code repo.

Preview: https://pr1217--matrix-org-previews.netlify.app

### CODE REVIEW

**Comment by afranke** [comment]
https://www.dittochat.org/ is a thing, the www seem required. Do you mind adjusting your patch?

**Comment by afranke** [comment]
@annie-elequin might want to know about this too.

**Comment by jaller94** [comment]
Nice catch. I didn't notice the `www.` subdomain.

**Comment by annie-elequin** [comment]
Just got back from vacation, thanks for this!

**Pull request merged**
