### PR TITLE
Update dependencies in gatsby/

### PR DESCRIPTION
**Pull request by afranke**
This is the result of `npm audit fix` (without `--force`), which was suggested by `npm i` because

```
found 1840 vulnerabilities (105 low, 95 moderate, 1638 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

### CODE REVIEW

**Comment by afranke** [comment]
Let me push an update to sign-off the commit.

**Review by MadLittleMods — APPROVED** [review]
LGTM 👍 Tested that site still works locally

Before:
```
found 1844 vulnerabilities (105 low, 95 moderate, 1642 high, 2 critical) in 3369 scanned packages
  run `npm audit fix` to fix 1793 of them.
  14 vulnerabilities require semver-major dependency updates.
  37 vulnerabilities require manual review. See the full report for details.
```

After:
```
found 49 vulnerabilities (5 low, 11 moderate, 32 high, 1 critical) in 3362 scanned packages
  run `npm audit fix` to fix 30 of them.
  9 vulnerabilities require semver-major dependency updates.
  10 vulnerabilities require manual review. See the full report for details.
```

**Comment by afranke** [comment]
Regarding the “after”, I did see that it didn’t fix everything, but I figured this could come as a later PR, once I had a chance to take a closer look.

**Comment by MadLittleMods** [comment]
@afranke It's a completely fine iteration 🚀 Let's ship it!

**Pull request merged**
