### PR TITLE
Update chatty information

### PR DESCRIPTION
**Pull request by agx**

### CODE REVIEW

**Review by MTRNord — APPROVED** [review]
Thank you!

**Comment by agx** [comment]
Thanks for approving this so quickly! What are the requirements to make a client a "featured client" ? I was cautious to add that.

**Comment by MTRNord** [comment]
> Thanks for approving this so quickly! What are the requirements to make a client a "featured client" ? I was cautious to add that.

Hi :) Currently there are no formal requirements defined, so this ends up being a decision between me and Thib as essentially the core editors of the website. There are plans to formalise this eventually, but our TODO list sadly doesn't have much of a priority for this currently. :/ So we take a rule of thumb in terms of "is maintained", "is usable by our grandparents" and "is visually pleasing". Many of these are subjective.

We also learned that clients which clearly feel unfinished or "Beta" are usually not appreciated by the community to be featured.

However, I had a thought as well that it might be interesting to list "upcoming" clients as semi-featured clients as well. https://github.com/matrix-org/matrix.org/issues/2443 there wasn't a deeper thought or talk about this however at this time.

**Comment by agx** [comment]
Thanks for the details: maybe to clarify: I wasn't thinking that Chatty is ready by now. I was more checking for the criteria list (as I figured matrix upstream would have good idea about user expectations) so that we could work towards it.

**Comment by MTRNord** [comment]
> Thanks for the details: maybe to clarify: I wasn't thinking that Chatty is ready by now. I was more checking for the criteria list (as I figured matrix upstream would have good idea about user expectations) so that we could work towards it.

hm yeah a checklist currently doesnt exist.

**Comment by agx** [comment]
If any criteria come to mind maybe just dump them here? Not as a binary in or out list but just to get an idea which can maybe later on be formalized?

**Pull request merged**
