### PR TITLE
Add header anchors

### LINKED ISSUE #1760: Anchors don't appear for titles in the blog posts
Zola supports anchor insertion: https://www.getzola.org/documentation/content/linking/#anchor-insertion

### LINKED ISSUE #2367: Add clickable anchor links to get links to sections
especially in TWIM, I want to link to sections similar how I can in the spec. It is technically already possible since the anchors get generated, but one has to "guess" them manually to do it.

### PR DESCRIPTION
**Pull request by MTRNord**
Fixes #2367
Fixes #1760

It seems to work I guess? We can improve upon it at a later stage with some design perhaps but this seems sufficient and fixes long standing annoyance

image

### CODE REVIEW

**Comment by HarHarLinks** [comment]
any test deployment?

**Comment by thibaultamartin** [comment]
Also supersedes #2009. I can't say I'm a huge fan of having to add something of the frontmatter of every single post, but we can adopt it and report to the zola maintainers that it'd be useful to have an option at the folder level

**Comment by MTRNord** [comment]
> any test deployment?

Apparently cloudflare bot was sleepy on this one...

**Comment by MTRNord** [comment]
> Can you squeeze in the 2024/12/_index.md file?

Done

**Review by thibaultamartin — APPROVED** [review]
I'm sad to approve it, but there is no way around it for now. Thanks for tackling it.

Ideally if you could also update the `CONTRIBUTE.md` to point out that the `insert_anchor_links` needs to be in the `month/_index.md` that would be great. Not blocking on it, we can do in a separate PR if you want.

**Pull request merged**
