### PR TITLE
Feature Syphon on clients page

### PR DESCRIPTION
**Pull request by TR-SLimey**
I forgot to do this in the original PR

### CODE REVIEW

**Comment by 0x1a8510f2** [comment]
@benparsons I noticed this PR is still open so was wondering if there's anything I need to do to get it merged? ( I changed accounts but this is still me :P )

**Comment by MadLittleMods** [comment]
Previous PR for reference: https://github.com/matrix-org/matrix.org/pull/961

Tested locally and looks good 👍 

http://localhost:8000/clients/


http://localhost:8000/docs/projects/client/syphon

**Comment by MadLittleMods** [comment]
Merged 🚀 Thanks for documenting your project @0x1a8510f2 (formerly @TR-SLimey) 😄

**Comment by 0x1a8510f2** [comment]
Thanks @MadLittleMods! Although this is @ereio 's project and I'm only helping out :D

**Pull request merged**
