### PR TITLE
Fix application services guide to use kramdown style code blocks

### PR DESCRIPTION
**Pull request by aaronraimist**
Better #238

### CODE REVIEW

**Comment by richvdh** [comment]
thanks, let's try it!

**Comment by richvdh** [comment]
well, that looks a lot better! https://matrix.org/docs/guides/application_services.html

**Comment by richvdh** [comment]
(and yes, it is a weird format. I rather wonder if we shouldn't instead be configuring kramdown to read GFM instead of its own funny dialect)

**Comment by aaronraimist** [comment]
Looks better but now you can't copy the examples without also getting the line numbers.

**Comment by richvdh** [comment]
ugh. yes.

**Comment by aaronraimist** [comment]
You could change this: coderay_line_numbers

https://kramdown.gettalong.org/rdoc/Kramdown/Options.html

**Comment by aaronraimist** [comment]
or just get rid of the syntax highlighting, although it think it looks good

**Comment by richvdh** [comment]
I don't seem to be able to get any changes in _config.yml to work, and I've now spent more time on this than I really wanted to :/

**Comment by aaronraimist** [comment]
Yeah just go ahead and remove the "yaml" and "python" bits from this patch and the syntax highlighting will go away along with the line numbers.

**Comment by richvdh** [comment]
[I suspect that the fact that the versions of jekyll and kramdown on our build server are prehistoric doesn't help anything]

**Pull request merged**
