### PR TITLE
Add 'bot' category to projects templates

### LINKED ISSUE #118: Should there be a «bot» category for Matrix projects? n/t

### PR DESCRIPTION
**Pull request by Matrixcoffee**
Fixes #118: Should there be a "bot" category for Matrix projects?

### CODE REVIEW

**Comment by Matrixcoffee** [comment]
Signed-off-by: Маrtіn vаո Βeіlеn (@Coffee:matrix.org)

**Comment by Matrixcoffee** [comment]
Signed-off-by: Маrtіn vаո Βeіlеn (`@Coffee:matrix.org`)

**Comment by richvdh** [comment]
lgtm but let's get #122 sorted

**Comment by Matrixcoffee** [comment]
I've added the changes suggested in #122 to this PR, as in my mind there are 2 logical operations:

* Firstly, add support for the category, and
* Secondly, actually move relevant projects into that category

LMK if there's something else you need me to do.

**Pull request merged**
