### PR TITLE
Fixed unrecognized expression: #what-is-matrix%3F

### PR DESCRIPTION
**Pull request by realvineeths**
Closes https://github.com/matrix-org/matrix.org/issues/1508

The issue is solved by eliminating the special characters, which used to show Uncaught Error: Syntax error, unrecognized expression.
Now its good to go.

### CODE REVIEW

**Comment by MTRNord** [comment]
This doesn't seem to solve that issue but instead makes these links invalid.

**Comment by realvineeths** [comment]
> This doesn't seem to solve that issue but instead makes these links invalid.
But its working when i ran locally in my machine.

**Comment by MTRNord** [comment]
> The link would be invalid if the href link does not match the id, but i have changed even the id. Please correct me if that would lead to an error.

Turns out indeed the links are valid. Does the icon still work though? The %3F afaik refers to the icon. so deleting % might break this

**Comment by realvineeths** [comment]
> > The link would be invalid if the href link does not match the id, but i have changed even the id. Please correct me if that would lead to an error.
> 
> Turns out indeed the links are valid. Does the icon still work though? The %3F afaik refers to the icon. so deleting % might break this
There is no issue of such all the icons are still working.

**Comment by thibaultamartin** [comment]
Closing this PR as obsolete since it doesn't target the rewrite of the website

**Pull request closed without merging**
