### PR TITLE
Fix ement.el breaking due to invalid html (a inside of a)

### LINKED ISSUE #2380: ecosystem/clients page not rendered correctly
Since merging https://github.com/matrix-org/matrix.org/pull/2366, it seems that something in the `clients.html` template is not rendering correctly.  Here's a screenshot of the rendered HTML and one of the DOM, showing that the `{% for client in clients %}` block at the bottom of the template is doing something weird with the newly added client's card.

bug

dom

Not being familiar with Zola and Tera directly (though they are similar to Hugo), I can't discern the problem quickly enough, so I'll leave this bug report.  Thanks.

### PR DESCRIPTION
**Pull request by MTRNord**
Fixes #2380

### CODE REVIEW

**Comment by MTRNord** [comment]
This PR requires zola 0.18.0 :/ Hence cloudflare fails

**Comment by thibaultamartin** [comment]
@guillaumevillemont can you could update the version of Zola CF Pages?

**Comment by guillaumevillemont** [comment]
> can you could update the version of Zola CF Pages?

I've done it for previews deployments and it's happy. Should I do it now for the production too ?  I'm not sure about backward compatible Zola is (like, if you'd merge other PR before this one for example)

**Comment by MTRNord** [comment]
> > can you could update the version of Zola CF Pages?
> 
> I've done it for previews deployments and it's happy. Should I do it now for the production too ?  I'm not sure about how backward compatible Zola is (like, if you'd merge other PR before this one for example)

If it works in the preview it works in production as well. According to the changelog there have been no breaking changes and the ci seems to be happy as well :) so imho it's ready for prod too.

**Comment by guillaumevillemont** [comment]
@MTRNord alright done, it's using v0.18.0 everywhere now !

**Comment by MTRNord** [comment]
> @MTRNord alright done, it's using v0.18.0 everywhere now !

Thanks @guillaumevillemont ! 🦆

**Review by thibaultamartin — APPROVED** [review]

**Pull request merged**
