### PR TITLE
Added fluffychat domain to content security policy directive

### LINKED ISSUE #878: FluffyChat screenshots are missing on matrix.org/clients
**Describe the bug**
Browsers refuse to load the screenshot of FluffyChat on subpage /clients (https://matrix.org/clients/) due to a violation of a content security policy directive.

Output of Chromiums consolse:
```
Refused to load the image 'https://fluffychat.im/assets/images/screenshot.png' because it violates the following Content Security Policy directive: "img-src 'self' data: https://matomo.riot.im https://*.twitter.com https://*.twimg.com https://github.com https://*.githubusercontent.com https://*.gitlab.io".
```

**To Reproduce**
1. Go to https://matrix.org
2. Click on "Matrix Live" and "Clients" to get to the page (https://matrix.org/clients/)

**Expected behavior**
Webpage should show a image for every client (mobile and desktop as well as web based ones).

**Screenshots**
Bildschirmfoto_2020-11-16_16-43-04
Bildschirmfoto_2020-11-16_16-45-14
Bildschirmfoto_2020-11-16_16-45-28

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.2
 - Browser: Chromium (and Firefox)
 - Version: 86.0.4240.75 (Firefox: 82.0.3)

### PR DESCRIPTION
**Pull request by maxkratz**
Closes #878.

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
we should inline these images instead, in my opinion.

**Comment by maxkratz** [comment]
> we should inline these images instead, in my opinion.

Yes, this would be a nice solution to this. Do we/I have to get permission to integrate the images?

**Comment by benparsons** [comment]
We should definitely inline them. I don't think anyone will object to this but cc @Sorunome for vis

**Comment by Sorunome** [comment]
@ChristianPauly has the last say on everything-fluffychat, not soru

That being said, he did say in chat that he is ok with that

**Comment by maxkratz** [comment]
I have a (local) commit with inline image(s) ready, but I'll wait for a "okay" from @ChristianPauly before pushing.

**Comment by ChristianPauly** [comment]
> I have a (local) commit with inline image(s) ready, but I'll wait for a "okay" from @ChristianPauly before pushing.

okay :-)

**Review by benparsons — APPROVED** [review]
lgtm

**Pull request merged**
