### PR TITLE
Update mautrix things

### PR DESCRIPTION
**Pull request by tulir**
.

Preview: https://pr1085--matrix-org-previews.netlify.app

### CODE REVIEW

**Comment by afranke** [comment]
@tulir I hopefully fixed the CI feature yesterday, can I ask for another rebase on top of current master? Sorry for the inconvenience.

**Comment by afranke** [comment]
Sadly the netlify preview deployment [timed out](https://github.com/matrix-org/matrix.org/actions/runs/1534738862). I have increased the duration, but that requires yet another rebase.

**Comment by richvdh** [comment]
> but that requires yet another rebase.

no it doesn't - it just needs us to rerun the workflows on this PR.

**Comment by afranke** [comment]
> > but that requires yet another rebase.
> 
> no it doesn't - it just needs us to rerun the workflows on this PR (in progress!)

I did that though, and I got the time out after that one. It’s run #2.

**Comment by afranke** [comment]
But I can see that it indeed worked this time. Not sure why mine failed, but well… now we have a preview, we now it works for external contributors, and I can finally finish reviewing this. That’s what counts. Thanks for re-re-running.

**Review by afranke — APPROVED** [review]
Looks great, cheers.

**Pull request merged**
